srhinow.beekeeping_manager.api:
  path: /api/{entityId}
  defaults:
    _controller: netzmacht.contao_workflow.backend.step_controller
    _scope: "backend"
    _token_check: true
    _custom_backend_view: true
    _backend_module: workflow