<?php
/**
 * TL_ROOT/system/modules/beekeeping_management/languages/de/tl_bkm_bee_breed.php
 *
 * Contao extension: beekeeping_management
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['name'][0]			= 'Bienen-Rassen';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['name'][1]        	= 'die Art der Bienen-Rasse wie Carnica,dunkle Biene etc.';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['short'][0]			= 'Abkürzung';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['short'][1]        	= 'die Art der Bienen-Rasse als Abkürzung: AMC, AMM';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['notiz'][0]       = 'Bemerkung';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['notiz'][1]       = 'Zusätzliche Eigenschaften zu dieser Bienen-Rasse.';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['sorting'][0]		= 'Sortierung';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['sorting'][1]		= 'Sortierungsplatz in einer eventuelle Listen-Darstellung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['new'][0]                          = 'Neue Bienen-Rasse';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['new'][1]                          = 'Eine neue Bienen-Rasse anlegen.';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['edit'][0]                         = 'Bienen-Rasse bearbeiten';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['edit'][1]                         = 'Bienen-Rasse ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['copy'][0]                         = 'Bienen-Rasse duplizieren';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['copy'][1]                         = 'Bienen-Rasse ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['delete'][0]                       = 'Bienen-Rasse löschen';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['delete'][1]                       = 'Bienen-Rasse ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['show'][0]                         = 'Bienen-Rassendetails anzeigen';
$GLOBALS['TL_LANG']['tl_bkm_bee_breed']['show'][1]                         = 'Details für Bienen-Rasse ID %s anzeigen.';

