<?php
/**
 * TL_ROOT/system/modules/beekeeping_management/languages/de/tl_bkm_population_size.php
 *
 * Contao extension: beekeeping_management
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bkm_population_size']['text'][0]         = 'Begriff';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['text'][1]         = 'ausgeschriebene Begriff wie er auch angezeigt wird';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['kurz'][0]			= 'Kurz';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['kurz'][1]        	= 'Abkürzung für schmale Tabellendarstellung';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['sorting'][0]		= 'Sortierung';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['sorting'][1]		= 'Sortierungsplatz in einer eventuelle Listen-Darstellung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bkm_population_size']['new'][0]                          = 'Neue Volksstärke';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['new'][1]                          = 'Eine neue Volksstärke anlegen.';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['edit'][0]                         = 'Volksstärke bearbeiten';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['edit'][1]                         = 'Volksstärke ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['copy'][0]                         = 'Volksstärke duplizieren';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['copy'][1]                         = 'Volksstärke ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['delete'][0]                       = 'Volksstärke löschen';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['delete'][1]                       = 'Volksstärke ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['show'][0]                         = 'Volksstärkedetails anzeigen';
$GLOBALS['TL_LANG']['tl_bkm_population_size']['show'][1]                         = 'Details für Volksstärke ID %s anzeigen.';

