<?php
/**
 * TL_ROOT/system/modules/beekeeping_management/languages/de/tl_bk_bkm_bee_prey.php
 *
 * Contao extension: beekeeping_management
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['nr'][0]			= 'Beuten-Nummer';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['nr'][1]        	= 'nur Zahl eingeben';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['frame_dimension'][0]       = 'Rähmchenmaß';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['frame_dimension'][1]       = 'Wählen sie das Rähmchenmaß dieser Beute aus.';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['notiz'][0]       = 'Bemerkung';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['notiz'][1]       = 'Zusätzliche Eigenschaften zu dieser Beute.';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['sorting'][0]		= 'Sortierung';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['sorting'][1]		= 'Sortierungsplatz in einer eventuelle Listen-Darstellung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['new'][0]                          = 'Neue Beute';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['new'][1]                          = 'Eine neue Beute anlegen.';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['edit'][0]                         = 'Beute bearbeiten';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['edit'][1]                         = 'Beute ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['copy'][0]                         = 'Beute duplizieren';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['copy'][1]                         = 'Beute ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['delete'][0]                       = 'Beute löschen';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['delete'][1]                       = 'Beute ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['show'][0]                         = 'Beutendetails anzeigen';
$GLOBALS['TL_LANG']['tl_bk_bkm_bee_prey']['show'][1]                         = 'Details für Beute ID %s anzeigen.';

