<?php
/**
 * TL_ROOT/system/modules/beekeeping_management/languages/de/tl_bkm_frame_dimensions.php
 *
 * Contao extension: beekeeping_management
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['name'][0]         = 'Bezeichnung';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['name'][1]         = 'Angabe der Rähmchengrößen-Bezeichnung.';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['width'][0]			= 'Breite';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['width'][1]        	= 'Breitenangabe';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['height'][0]			= 'Höhe';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['height'][1]        	= 'Höhenangabe';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['sorting'][0]		= 'Sortierung';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['sorting'][1]		= 'Sortierungsplatz in einer eventuelle Listen-Darstellung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['new'][0]                          = 'Neue Rähmchengröße';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['new'][1]                          = 'Eine neue Rähmchengröße anlegen.';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['edit'][0]                         = 'Rähmchengröße bearbeiten';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['edit'][1]                         = 'Rähmchengröße ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['copy'][0]                         = 'Rähmchengröße duplizieren';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['copy'][1]                         = 'Rähmchengröße ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['delete'][0]                       = 'Rähmchengröße löschen';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['delete'][1]                       = 'Rähmchengröße ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['show'][0]                         = 'Rähmchengrößedetails anzeigen';
$GLOBALS['TL_LANG']['tl_bkm_frame_dimensions']['show'][1]                         = 'Details für Rähmchengröße ID %s anzeigen.';

