<?php
/**
 * TL_ROOT/system/modules/beekeeping_management/languages/de/tl_bkm_location.php
 *
 * Contao extension: beekeeping_management
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bkm_location']['text'][0]         	= 'Begriff';
$GLOBALS['TL_LANG']['tl_bkm_location']['text'][1]         	= 'ausgeschriebene Begriff wie er auch angezeigt wird';
$GLOBALS['TL_LANG']['tl_bkm_location']['kurz'][0]			= 'Kurz';
$GLOBALS['TL_LANG']['tl_bkm_location']['kurz'][1]        	= 'Abkürzung für schmale Tabellendarstellung';
$GLOBALS['TL_LANG']['tl_bkm_location']['sorting'][0]		= 'Sortierung';
$GLOBALS['TL_LANG']['tl_bkm_location']['sorting'][1]		= 'Sortierungsplatz in einer eventuelle Listen-Darstellung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bkm_location']['new'][0]                          = 'Neuer Standort';
$GLOBALS['TL_LANG']['tl_bkm_location']['new'][1]                          = 'Ein neuer Standort anlegen.';
$GLOBALS['TL_LANG']['tl_bkm_location']['edit'][0]                         = 'Standort bearbeiten';
$GLOBALS['TL_LANG']['tl_bkm_location']['edit'][1]                         = 'Standort ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bkm_location']['copy'][0]                         = 'Standort duplizieren';
$GLOBALS['TL_LANG']['tl_bkm_location']['copy'][1]                         = 'Standort ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bkm_location']['delete'][0]                       = 'Standort löschen';
$GLOBALS['TL_LANG']['tl_bkm_location']['delete'][1]                       = 'Standort ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bkm_location']['show'][0]                         = 'Standortdetails anzeigen';
$GLOBALS['TL_LANG']['tl_bkm_location']['show'][1]                         = 'Details für Standort ID %s anzeigen.';

