<?php
/**
 * TL_ROOT/system/modules/beekeeping_management/languages/de/tl_bk_bkm_gentleness.php
 *
 * Contao extension: beekeeping_management
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['text'][0]         = 'Begriff';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['text'][1]         = 'ausgeschriebene Begriff wie er auch angezeigt wird';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['kurz'][0]			= 'Kurz';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['kurz'][1]        	= 'Abkürzung für schmale Tabellendarstellung';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['sorting'][0]		= 'Sortierung';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['sorting'][1]		= 'Sortierungsplatz in einer eventuelle Listen-Darstellung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['new'][0]                          = 'Neue Sanftmut';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['new'][1]                          = 'Eine neue Sanftmut anlegen.';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['edit'][0]                         = 'Sanftmut bearbeiten';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['edit'][1]                         = 'Sanftmut ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['copy'][0]                         = 'Sanftmut duplizieren';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['copy'][1]                         = 'Sanftmut ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['delete'][0]                       = 'Sanftmut löschen';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['delete'][1]                       = 'Sanftmut ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['show'][0]                         = 'Sanftmutdetails anzeigen';
$GLOBALS['TL_LANG']['tl_bk_bkm_gentleness']['show'][1]                         = 'Details für Sanftmut ID %s anzeigen.';

