<?php
/**
 * TL_ROOT/system/modules/beekeeping_management/languages/de/tl_bkm_feed_quality.php
 *
 * Contao extension: beekeeping_management
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['name'][0]			= 'Futter-Bewertung';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['name'][1]        	= 'Die Bewertung vom Futter z.B. sehr gut, gut, mittel, schlecht, sehr schlecht';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['short'][0]			= 'Abkürzung';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['short'][1]        	= 'die Futter-Bewertung als Abkürzung: 1,2,3,...';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['notiz'][0]       = 'Bemerkung';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['notiz'][1]       = 'Zusätzliche Bewertung zu diesem Eintrag';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['sorting'][0]		= 'Sortierung';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['sorting'][1]		= 'Sortierungsplatz in einer eventuelle Listen-Darstellung';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['new'][0]                          = 'Neue Futter-Bewertung';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['new'][1]                          = 'Eine neue Futter-Bewertung anlegen.';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['edit'][0]                         = 'Futter-Bewertung bearbeiten';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['edit'][1]                         = 'Futter-Bewertung ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['copy'][0]                         = 'Futter-Bewertung duplizieren';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['copy'][1]                         = 'Futter-Bewertung ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['delete'][0]                       = 'Futter-Bewertung löschen';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['delete'][1]                       = 'Futter-Bewertung ID %s löschen.';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['show'][0]                         = 'Futter-Bewertungndetails anzeigen';
$GLOBALS['TL_LANG']['tl_bkm_feed_quality']['show'][1]                         = 'Details für Futter-Bewertung ID %s anzeigen.';

